baseURL = 'https://atwish.org/'
languageCode = 'en-us'
title = 'Documentation At Your Wish'
theme = ['hugo-theme-relearn-main','hugo-notice']


sectionPagesMenu = 'main'


[params]
  Description = "Open source tools documentation written after trying step by step with Youtube videos. Apache Superset documentation. Keycloak documentation. Valkey documentation"


  [[params.themeVariant]]
    identifier = 'zen-light'

  
  [[params.meta]]
    description = "A place where you will find documentation as you wish it would be!"
    Author = "Shantanu Khond"
    

[markup.goldmark.parser.attribute]
block = true # default is false



[menu]
  [[menu.shortcuts]]
    identifier = 'ds'
    name = "<i class='fa-fw fab fa-github'></i> GitHub Profile"
    url = 'https://github.com/shantanukhond'
    weight = 10

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-play'></i> YouTube"
    url = 'https://youtube.com/@shantanuKhond/'
    weight = 11

  [[menu.shortcuts]]
    identifier = 'hugodoc'
    name = "<i class='fa-fw fas fa-usd'></i> Sponsor Us"
    url = 'https://www.buymeacoffee.com/shantanukhond'
    weight = 20

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-bullhorn'></i> Privacy Policy"
    url = '/privacy-policy.html'
    weight = 30
