baseURL = 'https://docs.shantanukhond.me/'
languageCode = 'en-us'
title = 'Learn With Shantanu'
theme = ['hugo-theme-relearn-main','hugo-notice']


sectionPagesMenu = 'main'


[params]
  favicon="lws.png"

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'

[markup.goldmark.parser.attribute]
block = true # default is false



[menu]
  [[menu.shortcuts]]
    identifier = 'ds'
    name = "<i class='fa-fw fab fa-github'></i> GitHub Profile"
    url = 'https://github.com/shantanukhond'
    weight = 10

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-camera'></i> Showcases"
    url = 'showcase/'
    weight = 11

  [[menu.shortcuts]]
    identifier = 'hugodoc'
    name = "<i class='fa-fw fas fa-bookmark'></i> Hugo Documentation"
    url = 'https://gohugo.io/'
    weight = 20

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-bullhorn'></i> Credits"
    url = 'more/credits/'
    weight = 30

  [[menu.shortcuts]]
    name = "<i class='fa-fw fas fa-tags'></i> Tags"
    url = 'tags/'
    weight = 40