name: Hugo Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.128.1'  # Change to your Hugo version

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0 
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/  # Change if your Hugo output directory is different
          remote-dir: ./  # Change to your cPanel public directory
